### ISSUE TITLE
Encountered a LuaComponentException

### ISSUE THREAD

**Issue by Richard333** [Zygahedron/Starbecue#6] opened 2022-06-02 08:04 UTC
Crash occurred when I was trying to use a teleporter on a planet to go to Auri's foodhall as a human while under the effects of a Transformation potion for the Draconis Race with the Full Dragon Reskin. Attempts to reload the character would always result in a fatal exception crash, looking in starbound's log file the cause that'd lead to it was a: 
[Error] Exception caught in client main-loop
(LuaComponentException) Duplicate callbacks named 'effect' in LuaBaseComponent
upon it warping you to your ship (I got no clue why it was warping me to my ship, my guess is I lost the cause in a prior log file when I first tried to teleport to Auri's foodhall).

Managed to fix it using a save editor (had to export it into JSON format first, then import it when I made changes) and deleting the effect sections of "sbqMysteriousPotionTF" (3 sections), 2 of which were minor duration sections and the last related to [starboundSpeciesAnimOverrides] mod. Just to be on the safe side I also deleted the same relevant passage in "speciesAnimOverrideData". They are also both located under the "statusController" section.

The relevant sections:

            "sbqMysteriousPotionTF": {
                "directives": "?replace;000000=bdbdbd?replace;700E00=6B9992;dc1f00=DFF1E5;be1b00=B0D8C7;951500=B0D8C7;FF2100=EDFFF3?replace;a38d59=865454;735e3a=60383E;f7e7b2=B48D87;d9c189=A27674",
                "gender": "male",
                "hairDirectives": "?replace;000000=bdbdbd?replace;700E00=6B9992;dc1f00=DFF1E5;be1b00=B0D8C7;951500=B0D8C7;FF2100=EDFFF3?replace;a38d59=865454;735e3a=60383E;f7e7b2=B48D87;d9c189=A27674?replace;700E00=6B9992;dc1f00=DFF1E5;be1b00=B0D8C7;951500=B0D8C7;FF2100=EDFFF3",
                "identity": {
                    "facialHairGroup": "",
                    "facialMaskGroup": "",
                    "hairGroup": "hair",
                    "hairType": "male34"
                },
                "mysteriousPotion": true,
                "permanent": true,
                "species": "dragon"
            },

            "speciesAnimOverrideData": {
                "directives": "?replace;000000=bdbdbd?replace;700E00=6B9992;dc1f00=DFF1E5;be1b00=B0D8C7;951500=B0D8C7;FF2100=EDFFF3?replace;a38d59=865454;735e3a=60383E;f7e7b2=B48D87;d9c189=A27674",
                "gender": "male",
                "hairDirectives": "?replace;000000=bdbdbd?replace;700E00=6B9992;dc1f00=DFF1E5;be1b00=B0D8C7;951500=B0D8C7;FF2100=EDFFF3?replace;a38d59=865454;735e3a=60383E;f7e7b2=B48D87;d9c189=A27674?replace;700E00=6B9992;dc1f00=DFF1E5;be1b00=B0D8C7;951500=B0D8C7;FF2100=EDFFF3",
                "identity": {
                    "facialHairGroup": "",
                    "facialMaskGroup": "",
                    "hairGroup": "hair",
                    "hairType": "male34"
                },
                "mysteriousPotion": true,
                "permanent": true,
                "species": "dragon"
            },

Other than the necessary mods, I have Frackin Universe, XS and ZZ Mechs (ZZ requires XS), Magmarock furniture, FU race compatibility patches for draconis and avali, and SSVM with almost all the add-ons people have made for it.
No clue how I even got this to happen but I thought I might as well report it. If needed I can provided the starbound log file and a before and after JSON file of my character with the deleted lines (also the line numbers they're on as well).

**Comment by WasabiRaptor** [comment] 2022-06-02 17:08
I haven't been able to intentionally replicate this error, but some other people have had it, I'm trying to figure it out, check back for a fix later

**Comment by Richard333** [comment] 2022-06-02 17:45
If it helps here is all the stuff I did before it crashed/happened:
Warped to Auri's, ran around the world twice, bought a few dozen random TF potion - a few select species ones - and a bunch of undo potions, kept drinking the random ones until I got Draconis, used a select species one to have a backup of it, kept drinking random potions until got a race starting with Sk (lizard like), used a select species one on that one as well, bought a Colony deed from Auri, left the few dozen potions on the ground, teleported to my home planet, messed around with the colony deed a bit trying to figure it out, it kept being unselectable for some reason or another at a house a bit away from the colony after summoning a tenant, used commands to kill those tenants as they didn't despawn upon removal of the deed, replaced a normal colony deed with one from Auri's shop, selected Draconis NPC, banged head against wall trying to find something with the Dragon tag, used TF potion I made for Draconis earlier, unequipped armor, forgot I needed a/the tool, used teleporter to go back to Auri's while holding a tool you get when using the transformation techs (see: Xeronious), crash happened.

**Comment by Richard333** [comment] 2022-06-02 19:48
Couldn't interact with it (hitting the interact key when it is selected when it's down in the world results in nothing), destroying it and then placing it back down results in it behaving as normal. Only happens on my colony/home planet (haven't tested on other planets). It also doesn't record the NPC it summoned so they never go away, hence why I had to use commands to kill them.

**Comment by WasabiRaptor** [comment] 2022-06-02 19:59
yeah that was a separate issue I just fixed, I had a script to make the vanilla deeds detect mine, but it wasn't working correctly and was causing it to break

also, the sbq vore NPCs will not ever be summoned by a vanilla deed, I don't add any UI to vanilla deeds, I don't make vanilla deeds save their NPC, that stuff is only on the sbq deed


as for the transformation causing a crash, I could not reproduce that error, but I did make a change to potentially fix what was the likely cause, and I'll probably close this issue in a few days if nobody else reports it

**Comment by WasabiRaptor** [comment] 2022-06-04 01:50
This issue just got solved for good, any effected players or worlds should become un corrupted next time they attempt to load

**Closed by WasabiRaptor** 2022-06-04 01:50 UTC
